<?
if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	die();
}

return [
	'css' => [
		'/bitrix/js/salescenter/app/dist/app.bundle.css',
		'/bitrix/components/bitrix/ui.sidepanel.wrappermenu/templates/.default/style.css',
		'/bitrix/components/bitrix/ui.button.panel/templates/.default/style.css',
	],
	'js' => '/bitrix/js/salescenter/app/dist/app.bundle.js',
	'rel' => [
		'bitrix24.phoneverify',
		'catalog.product-form',
		'crm.integration.analytics',
		'crm.messagesender.editor',
		'crm.router',
		'currency',
		'currency.currency-core',
		'landing.backend',
		'landing.pageobject',
		'main.core',
		'main.core.events',
		'main.loader',
		'main.popup',
		'popup',
		'rest.client',
		'salescenter.automation-stage',
		'salescenter.component.stage-block',
		'salescenter.component.stage-block.automation',
		'salescenter.component.stage-block.hint',
		'salescenter.component.stage-block.sms-message',
		'salescenter.component.stage-block.tile',
		'salescenter.component.stage-block.timeline',
		'salescenter.deliveryselector',
		'salescenter.lib',
		'salescenter.manager',
		'salescenter.marketplace',
		'salescenter.tile',
		'salescenter.timeline',
		'ui.analytics',
		'ui.buttons',
		'ui.buttons.icons',
		'ui.design-tokens',
		'ui.dialogs.messagebox',
		'ui.entity-selector',
		'ui.fonts.opensans',
		'ui.fonts.ruble',
		'ui.forms',
		'ui.icon-set.actions',
		'ui.icons.disk',
		'ui.notification',
		'ui.pinner',
		'ui.vue',
		'ui.vue.vuex',
	],
	'skip_core' => false,
];