import './slider-shell.css';
import './app.css';
import './block.css'
import './assessment.css';
import './failed-criteria.css';
import './criteria.css';
import './toolbar.css';
import './header.css';
import './popup.css';
import './settings.css';
