<?
$DB->Query("DELETE FROM b_event_type WHERE EVENT_NAME in ('IM_NEW_NOTIFY', 'IM_NEW_NOTIFY_GROUP', 'IM_NEW_MESSAGE', 'IM_NEW_MESSAGE_GROUP', 'IM_GUEST_INVITATION')");
$DB->Query("DELETE FROM b_event_message WHERE EVENT_NAME in ('IM_NEW_NOTIFY', 'IM_NEW_NOTIFY_GROUP', 'IM_NEW_MESSAGE', 'IM_NEW_MESSAGE_GROUP', 'IM_GUEST_INVITATION')");
?>