<?php

$event = \Bitrix\Main\UpdateSystem\Migration::getInstance()->event();

$event
	->register('main', 'OnAfterRegisterModule', '\Bitrix\Market\Tag\Manager', 'onAfterRegisterModule')
	->register('main', 'OnAfterUnRegisterModule', '\Bitrix\Market\Tag\Manager', 'onAfterUnRegisterModule')
	->register(
		'main',
		'OnAfterSetOption_~mp24_paid',
		'\Bitrix\Market\Integration\Rest\TagHandler',
		'onChangeSubscription',
	)
	->register(
		'main',
		'OnAfterSetOption_~mp24_paid_date',
		'\Bitrix\Market\Integration\Rest\TagHandler',
		'onChangeSubscription',
	)
	->register(
		'voximplant',
		'\Bitrix\Voximplant\Sip::OnAfterAdd',
		'\Bitrix\Market\Integration\Voximplant\TagHandler',
		'onChangeSip',
	)
	->register(
		'voximplant',
		'\Bitrix\Voximplant\Sip::OnAfterUpdate',
		'\Bitrix\Market\Integration\Voximplant\TagHandler',
		'onChangeSip',
	)
	->register(
		'voximplant',
		'\Bitrix\Voximplant\Sip::OnAfterDelete',
		'\Bitrix\Market\Integration\Voximplant\TagHandler',
		'onChangeSip',
	)
	->register(
		'landing',
		'onLandingPublication',
		'\Bitrix\Market\Integration\Landing\TagHandler',
		'onChangeLandingPublication',
	)
	->register(
		'landing',
		'onLandingAfterUnPublication',
		'\Bitrix\Market\Integration\Landing\TagHandler',
		'onChangeLandingPublication',
	)
	->register(
		'intranet',
		'onAfterChangeLeftMenuPreset',
		'\Bitrix\Market\Integration\Intranet\TagHandler',
		'onAfterChangeLeftMenuPreset',
	)
	->register(
		'main',
		'OnAfterSetOption_~PARAM_CLIENT_LANG',
		'\Bitrix\Market\Integration\Main\TagHandler',
		'onChangeClientLang',
	)
	->register(
		'main',
		'OnAfterSetOption_~controller_group_name',
		'\Bitrix\Market\Integration\Main\TagHandler',
		'onBitrix24LicenseChange',
	)
	->register(
		'imopenlines',
		'\Bitrix\ImOpenLines\Model\Config::OnAfterAdd',
		'\Bitrix\Market\Integration\ImOpenLines\TagHandler',
		'onChangeConfig',
	)
	->register(
		'imopenlines',
		'\Bitrix\ImOpenLines\Model\Config::OnAfterUpdate',
		'\Bitrix\Market\Integration\ImOpenLines\TagHandler',
		'onChangeConfig',
	)
	->register(
		'imopenlines',
		'\Bitrix\ImOpenLines\Model\Config::OnAfterDelete',
		'\Bitrix\Market\Integration\ImOpenLines\TagHandler',
		'onChangeConfig',
	)
	->register(
		'bizproc',
		'onAfterWorkflowTemplateAdd',
		'\Bitrix\Market\Integration\BizProc\TagHandler',
		'onEventAdd',
	)
	->register(
		'bizproc',
		'onAfterWorkflowTemplateDelete',
		'\Bitrix\Market\Integration\BizProc\TagHandler',
		'onEventDelete',
	)
	->register(
		'sale',
		'OnSalePaySystemUpdate',
		'\Bitrix\Market\Integration\Sale\TagHandler',
		'onUpdatePaySystem',
	)
	->register(
		'messageservice',
		'onGetSmsSenders',
		'\Bitrix\Market\Integration\Messageservice\TagHandler',
		'onGetMessageProvider',
	)
;
