<?php

if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	die();
}

if (!\Bitrix\Main\Loader::includeModule('booking'))
{
	return [];
}

return [
	'lang' => BX_ROOT.'/modules/booking/install/components/bitrix/booking/class.php',
	'css' => 'dist/booking.bundle.css',
	'js' => 'dist/booking.bundle.js',
	'rel' => [
		'booking.application.sku-resources-editor',
		'booking.application.yandex-integration-wizard',
		'booking.component.actions-popup',
		'booking.component.booking-card',
		'booking.component.button',
		'booking.component.client-popup',
		'booking.component.counter',
		'booking.component.counter-floating',
		'booking.component.empty-filter-results-popup',
		'booking.component.loader',
		'booking.component.mixin.loc-mixin',
		'booking.component.popup',
		'booking.component.statistics-popup',
		'booking.component.time-selector',
		'booking.component.whatsapp-popup-changes-sending-messages',
		'booking.const',
		'booking.core',
		'booking.lib.aha-moments',
		'booking.lib.analytics',
		'booking.lib.booking',
		'booking.lib.busy-slots',
		'booking.lib.cell',
		'booking.lib.check-booking-intersection',
		'booking.lib.currency-format',
		'booking.lib.date-period',
		'booking.lib.deal-helper',
		'booking.lib.drag',
		'booking.lib.duration',
		'booking.lib.filter-result-navigator',
		'booking.lib.grid',
		'booking.lib.help-desk',
		'booking.lib.in-interval',
		'booking.lib.is-real-id',
		'booking.lib.limit',
		'booking.lib.mouse-position',
		'booking.lib.range',
		'booking.lib.remove-booking',
		'booking.lib.remove-resource',
		'booking.lib.remove-wait-list-item',
		'booking.lib.request-revision-guard',
		'booking.lib.resolvable',
		'booking.lib.resources',
		'booking.lib.resources-date-cache',
		'booking.lib.side-panel-instance',
		'booking.lib.slot-ranges',
		'booking.lib.utils',
		'booking.provider.service.booking-actions-service',
		'booking.provider.service.booking-service',
		'booking.provider.service.calendar-service',
		'booking.provider.service.client-service',
		'booking.provider.service.dictionary-service',
		'booking.provider.service.main-page-service',
		'booking.provider.service.option-service',
		'booking.provider.service.resource-dialog-service',
		'booking.provider.service.resources-service',
		'booking.provider.service.sale-channels-service',
		'booking.provider.service.wait-list-service',
		'booking.resource-creation-wizard',
		'main.core',
		'main.core.events',
		'main.date',
		'main.loader',
		'main.popup',
		'ui.auto-launch',
		'ui.banner-dispatcher',
		'ui.cnt',
		'ui.counterpanel',
		'ui.date-picker',
		'ui.dialogs.messagebox',
		'ui.ears',
		'ui.entity-selector',
		'ui.hint',
		'ui.icon-set.actions',
		'ui.icon-set.animated',
		'ui.icon-set.api.core',
		'ui.icon-set.api.vue',
		'ui.icon-set.main',
		'ui.icon-set.outline',
		'ui.label',
		'ui.notification-manager',
		'ui.system.skeleton.vue',
		'ui.vue3',
		'ui.vue3.components.button',
		'ui.vue3.components.counter',
		'ui.vue3.components.rich-loc',
		'ui.vue3.directives.hint',
		'ui.vue3.vuex',
	],
	'skip_core' => false,
	'settings' => [
		'isAirTemplate' =>
			\Bitrix\Main\Loader::includeModule('intranet')
			&& class_exists(\Bitrix\Intranet\Integration\Templates\Air\AirTemplate::class)
			&& \Bitrix\Intranet\Integration\Templates\Air\AirTemplate::isEnabled()
		,
	],
];
