<?php

return [
	'extensions' => [
		'apptheme',
		'type',
		'alert',
		'haptics',
		'notify-manager',
		'tokens',
		'module',
		'utils/url',
		'utils/file',
		'assets/icons',
		'utils/object',
		'device/connection',
		'im:lib/theme',
		'im:messenger/loc',
		'im:messenger/assets/common',
		'im:messenger/const',
		'im:messenger/controller/user-profile',
		'im:messenger/controller/forward-selector',
		'im:messenger/lib/params',
		'im:messenger/lib/logger',
		'im:messenger/lib/feature',
		'im:messenger/lib/permission-manager',
		'im:messenger/lib/helper',
		'im:messenger/lib/emitter',
		'im:messenger/lib/reaction-assets-manager',
		'im:messenger/lib/ui/notification',
		'im:messenger/lib/ui/alert',
		'im:messenger/controller/dialog/lib/message-create-menu',
		'im:messenger/controller/dialog/lib/helper/text',
		'im:messenger/provider/services/analytics',
		'im:messenger/controller/selector/forward',
		'im:messenger/api/dialog-integration/message/context-menu',
		'im:messenger/lib/di/service-locator',
		'im:messenger/controller/file-download-menu',
	],
	'bundle' => [
		'./src/one-level/manager',
		'./src/one-level/view',

		'./src/multi-level/manager',
		'./src/multi-level/view',

		'./src/message-action-helper',
		'./src/controller',
		'./src/section',
		'./src/action',

		'./src/context/default',
		'./src/context/copilot',
		'./src/context/ai-assistant',
		'./src/saver/file-saver',
		'./src/saver/save-toast',
		'./src/saver/disk-saver',
		'./src/saver/base-saver',
	],
];
