<?php

return [
	'extensions' => [
		'disk/in-app-url/routes',
		'require-lazy/extension-loader',
		'in-app-url/const',
		'in-app-url/route',
		'in-app-url/routes',
		'in-app-url/routes/bitrix24',
		'in-app-url/routes/development-routes',
		'in-app-url/routes/market',
		'in-app-url/routes/note',
		'in-app-url/routes/settings',
		'in-app-url/routes/stafftrack',
		'in-app-url/routes/timeman',
		'in-app-url/url',
		'utils/string',
		'utils/url',
		'bizproc:in-app-url/routes',
		'calendar:in-app-url/routes',
		'call:in-app-url/routes',
		'crm:in-app-url/routes',
		'disk:in-app-url/routes',
		'im:in-app-url/routes',
		'intranet:in-app-url/routes',
		'lists:in-app-url/routes',
		'mail:in-app-url/routes',
		'sign:in-app-url/routes',
		'stafftrack:in-app-url/routes',
		'tasks:in-app-url/routes',
	],
	'bundle' => [
		'./src/in-app-extensions',
		'./src/in-app-url',
		'./src/module-routes',
	],
];
