<?php
$MESS["TASKS_BP_DOCUMENT_ENTITY_NAME"] = "Потік";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_0"] = "У потоці [flowUrl]{flowName}[/flowUrl] вже {totalTasksInQueue} завдання в очікуванні. Керувати навантаженням на співробітників ви можете в проєкті [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_1"] = "У потоці [flowUrl]{flowName}[/flowUrl] вже {totalTasksInQueue} завдання в очікуванні. Керувати навантаженням на співробітників ви можете в проєкті [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_QUEUE_PLURAL_2"] = "У потоці [flowUrl]{flowName}[/flowUrl] вже {totalTasksInQueue} завдань в очікуванні. Керувати навантаженням на співробітників ви можете в проєкті [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_0"] = "У потоці [flowUrl]{flowName}[/flowUrl] вже {totalTasksInProgress} завдання в роботі. Керувати навантаженням на співробітників ви можете в проєкті [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_1"] = "У потоці [flowUrl]{flowName}[/flowUrl] вже {totalTasksInProgress} завдання в роботі. Керувати навантаженням на співробітників ви можете в проєкті [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_BUSY_RESPONSIBLE_PLURAL_2"] = "У потоці [flowUrl]{flowName}[/flowUrl] вже {totalTasksInProgress} завдань в роботі. Керувати навантаженням на співробітників ви можете в проєкті [groupUrl]{groupName}[/groupUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_EFFICIENCY_LOWER_MESSAGE"] = "У потоці [flowUrl]{flowName}[/flowUrl] ефективність нижче {targetEfficiency}%. Проконтролюйте терміни виконання завдань.";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_ABSENT"] = "Співробітник, який розподіляв завдання в потоці [flowUrl]{flowName}[/flowUrl], відсутній. Тепер усі завдання призначатимуться вам, змінити спосіб розподілу завдань можна в [flowSettingsUrl]налаштуваннях потоку[/flowSettingsUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_MANUAL_DISTRIBUTOR_CHANGE_MESSAGE"] = "Співробітника, який розподіляв завдання в потоці [flowUrl]{flowName}[/flowUrl], звільнено. Тепер усі завдання призначатимуться вам, змінити спосіб розподілу завдань можна в [flowSettingsUrl]налаштуваннях потоку[/flowSettingsUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_ABSENT_MESSAGE"] = "У потоці [flowUrl]{flowName}[/flowUrl] усі завдання тепер розподіляються на вас, бо всі співробітники в черзі відсутні. Додати виконавців ви можете в [flowSettingsUrl]налаштуваннях потоку[/flowSettingsUrl].";
$MESS["TASKS_FLOW_NOTIFICATION_MESSAGE_FORCED_FLOW_SWITCH_TO_MANUAL_DISTRIBUTION_MESSAGE"] = "У потоці [flowUrl]{flowName}[/flowUrl] усі завдання тепер розподіляються на вас, бо в черзі не залишилося співробітників. Додати виконавців ви можете в [flowSettingsUrl]налаштуваннях потоку[/flowSettingsUrl].";
