CREATE TABLE IF NOT EXISTS hms_clinic (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    XML_ID VARCHAR(255) DEFAULT NULL,
    TITLE VARCHAR(255) NOT NULL,
    COMPANY_ID INT UNSIGNED DEFAULT NULL,
    --
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hms_office (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    XML_ID VARCHAR(255) DEFAULT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CLINIC_ID INT UNSIGNED DEFAULT NULL,
    IS_CONTINUOUS_SCHEME VARCHAR(1) NOT NULL DEFAULT 'N',
    --
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hms_doctor (
    ID INT UNSIGNED NOT NULL,
    XML_ID VARCHAR(255) DEFAULT NULL,
    OFFICE_ID INT UNSIGNED DEFAULT NULL,
    IS_CONTINUOUS_SCHEME VARCHAR(1) NOT NULL DEFAULT 'N',
    --
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hms_schedule (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    XML_ID VARCHAR(255) DEFAULT NULL,
    ACTIVE VARCHAR(1) NOT NULL DEFAULT 'N',
    CLINIC_ID INT UNSIGNED NOT NULL,
    DATE_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PARTICIPANTS TEXT DEFAULT NULL,
    MODE VARCHAR(1) NOT NULL DEFAULT 'D',
    PLAN_DATE DATE NOT NULL,
    NUMBER VARCHAR(50) NOT NULL,
    ASSIGNED_BY_ID INT NOT NULL,
    COMMENT VARCHAR(255) DEFAULT NULL,
    --
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hms_schedule_worktime (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    SCHEDULE_ID INT UNSIGNED NOT NULL,
    DOCTOR_ID INT UNSIGNED DEFAULT NULL,
    OFFICE_ID INT UNSIGNED DEFAULT NULL,
    WORKTIME_FROM DATETIME NOT NULL,
    WORKTIME_TO DATETIME NOT NULL,
    COLOR VARCHAR(7) DEFAULT NULL,
    DESCRIPTION VARCHAR(255) DEFAULT NULL,
    BREAKS TEXT DEFAULT NULL,
    --
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hms_shift_work (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    WORKTIMES TEXT DEFAULT NULL,
    --
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hms_filling_method (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(2) DEFAULT 'PR',
    SEGMENTS TEXT DEFAULT NULL,
    --
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hms_appointment (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    XML_ID VARCHAR(255) DEFAULT NULL,
    RESERVE_XML_ID VARCHAR(255) DEFAULT NULL,
    DATE_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TITLE VARCHAR(255) NOT NULL,
    STATUS_ID VARCHAR (50) DEFAULT NULL,
    SOURCE_TYPE CHAR(3) DEFAULT NULL,
    SOURCE_ID INT UNSIGNED DEFAULT NULL,
    CLINIC_ID INT UNSIGNED DEFAULT NULL,
    DOCTOR_ID INT UNSIGNED DEFAULT NULL,
    OFFICE_ID INT UNSIGNED DEFAULT NULL,
    SPECIALIZATION_ID INT UNSIGNED DEFAULT NULL,
    DATE_FROM DATETIME NOT NULL,
    DURATION INT NOT NULL,
    COMMENTS TEXT DEFAULT NULL,
    ASSIGNED_BY_ID INT UNSIGNED NOT NULL,
    --
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS hms_appointment_reserve_doctor (
    APPOINTMENT_ID INT UNSIGNED NOT NULL,
    DOCTOR_ID INT UNSIGNED NOT NULL,
    --
    PRIMARY KEY (APPOINTMENT_ID, DOCTOR_ID)
);

CREATE TABLE IF NOT EXISTS hms_appointment_reserve_office (
    APPOINTMENT_ID INT UNSIGNED NOT NULL,
    OFFICE_ID INT UNSIGNED NOT NULL,
    --
    PRIMARY KEY (APPOINTMENT_ID, OFFICE_ID)
);

CREATE TABLE IF NOT EXISTS hms_appointment_reserve_specialization (
    APPOINTMENT_ID INT UNSIGNED NOT NULL,
    SPECIALIZATION_ID INT UNSIGNED NOT NULL,
    --
    PRIMARY KEY (APPOINTMENT_ID, SPECIALIZATION_ID)
);

CREATE TABLE IF NOT EXISTS hms_appointment_reserve_date (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    APPOINTMENT_ID INT UNSIGNED NOT NULL,
    DATE_FROM DATETIME NOT NULL,
    DATE_TO DATETIME NOT NULL,
    --
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS hms_appointment_contact (
    APPOINTMENT_ID INT UNSIGNED NOT NULL,
    CONTACT_ID INT UNSIGNED NOT NULL,
    SORT INT UNSIGNED DEFAULT 0,
    IS_PRIMARY VARCHAR(1) DEFAULT 'N',
    --
    PRIMARY KEY(APPOINTMENT_ID, CONTACT_ID)
);

CREATE TABLE IF NOT EXISTS hms_specialization (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    XML_ID VARCHAR(255) DEFAULT NULL,
    TITLE VARCHAR(255) NOT NULL,
    RECEIVE_TYPE VARCHAR(255) NOT NULL,
    SERVICES MEDIUMTEXT NOT NULL,
    --
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS hms_doctor_specialization (
    SPECIALIZATION_ID INT UNSIGNED NOT NULL,
    DOCTOR_ID INT UNSIGNED NOT NULL,
    --
    PRIMARY KEY(DOCTOR_ID, SPECIALIZATION_ID)
);

CREATE TABLE IF NOT EXISTS hms_office_specialization (
    SPECIALIZATION_ID INT UNSIGNED NOT NULL,
    OFFICE_ID INT UNSIGNED NOT NULL,
    --
    PRIMARY KEY(OFFICE_ID, SPECIALIZATION_ID)
);

CREATE TABLE IF NOT EXISTS hms_receive (
    ID INT UNSIGNED NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    DATE_START DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATE_END DATETIME DEFAULT NULL,
    ---
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS hms_appointment_deal (
    APPOINTMENT_ID INT UNSIGNED NOT NULL,
    DEAL_ID INT UNSIGNED NOT NULL,
    ---
    PRIMARY KEY(APPOINTMENT_ID, DEAL_ID)
);

CREATE TABLE IF NOT EXISTS hms_receive_base (
    ID INT UNSIGNED NOT NULL,
    DIAGNOSIS TEXT DEFAULT '',
    REPORT TEXT DEFAULT '',
    RECOMMENDATION TEXT DEFAULT '',
    ---
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS hms_vhi_service_type (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    XML_ID VARCHAR(255) DEFAULT NULL,
    TITLE VARCHAR(255) NOT NULL,
    SERVICES MEDIUMTEXT NOT NULL,
    ---
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS hms_vhi_type (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    XML_ID VARCHAR(255) DEFAULT NULL,
    TITLE VARCHAR(255) NOT NULL,
    ---
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS hms_vhi_type_vhi_service_type (
    VHI_TYPE_ID INT UNSIGNED NOT NULL,
    VHI_SERVICE_TYPE_ID INT UNSIGNED NOT NULL,
    ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',
    ---
    PRIMARY KEY(VHI_TYPE_ID, VHI_SERVICE_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS hms_vhi_storage (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    VHI_TYPE_ID INT UNSIGNED DEFAULT NULL,
    NUMBER VARCHAR(255) NOT NULL,
    NAME VARCHAR(50) DEFAULT NULL,
    LAST_NAME VARCHAR(50) DEFAULT NULL,
    SECOND_NAME VARCHAR(50) DEFAULT NULL,
    BIRTHDATE DATE DEFAULT NULL,
    DATE_START DATE NOT NULL,
    DATE_END DATE NOT NULL,
    GENDER VARCHAR(1) NOT NULL DEFAULT 'M',
    ADDRESS VARCHAR(255) DEFAULT NULL,
    PHONE VARCHAR(32) NOT NULL,
    ---
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS hms_vhi (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    XML_ID VARCHAR(255) DEFAULT NULL,
    CONTACT_ID INT UNSIGNED NOT NULL,
    VHI_STORAGE_ID INT UNSIGNED DEFAULT NULL,
    VHI_TYPE_ID INT UNSIGNED NOT NULL,
    ACTIVE VARCHAR(1) NOT NULL DEFAULT 'Y',
    NUMBER VARCHAR(255) NOT NULL,
    DATE_START DATE DEFAULT NULL,
    DATE_END DATE DEFAULT NULL,
    ---
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS hms_product_row (
    ID INT UNSIGNED NOT NULL,
    IS_VHI VARCHAR(1) NOT NULL DEFAULT 'N',
    TEETH TEXT DEFAULT NULL,
    ---
    PRIMARY KEY(ID)
);
