<?php

if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	die();
}

return [
	'css' => 'dist/resource-creation-wizard.bundle.css',
	'js' => 'dist/resource-creation-wizard.bundle.js',
	'rel' => [
		'ui.vue3',
		'booking.component.mixin.loc-mixin',
		'booking.model.notifications',
		'booking.model.resource-creation-wizard',
		'booking.lib.side-panel-instance',
		'main.loader',
		'booking.core',
		'ui.notification-manager',
		'crm.messagesender',
		'booking.provider.service.resources-service',
		'booking.lib.analytics',
		'booking.model.resource-types',
		'booking.provider.service.resources-type-service',
		'booking.component.reminder',
		'ui.entity-selector',
		'main.core.events',
		'booking.lib.timezone',
		'ui.buttons',
		'booking.lib.duration',
		'ui.forms',
		'ui.layout-form',
		'booking.lib.aha-moments',
		'ui.vue3.components.menu',
		'ui.vue3.directives.hint',
		'ui.icon-set.actions',
		'ui.icon-set.crm',
		'ui.hint',
		'booking.component.switcher',
		'booking.provider.service.resource-creation-wizard-service',
		'main.popup',
		'main.core',
		'main.date',
		'booking.component.popup',
		'booking.component.button',
		'booking.component.help-desk-loc',
		'ui.icon-set.api.vue',
		'ui.icon-set.api.core',
		'ui.vue3.components.rich-loc',
		'ui.vue3.vuex',
		'ui.icon-set.main',
		'booking.const',
		'booking.component.cycle-popup',
	],
	'skip_core' => false,
];
