import { Outline as OutlineIcons } from 'ui.icon-set.api.vue';

// Temporary map: icon IDs currently differ between mobile and web. To be removed once unified IDs are in place.
export const IconMap = {
	chevron_to_the_left: OutlineIcons.CHEVRON_LEFT_L,
	chevron_to_the_right: OutlineIcons.CHEVRON_RIGHT_L,
	chevron_up: OutlineIcons.CHEVRON_TOP_L,
	chevron_down: OutlineIcons.CHEVRON_DOWN_L,
	arrow_to_the_left: OutlineIcons.ARROW_LEFT_L,
	arrow_to_the_right: OutlineIcons.ARROW_RIGHT_L,
	arrow_top: OutlineIcons.ARROW_TOP_L,
	arrow_down: OutlineIcons.ARROW_DOWN_L,
	circle_check: OutlineIcons.CIRCLE_CHECK,
	alert_accent: OutlineIcons.ALERT_ACCENT,
	clock: OutlineIcons.CLOCK,
	search: OutlineIcons.SEARCH,
	fire: OutlineIcons.FIRE,
	task: OutlineIcons.TASK,
	crm: OutlineIcons.CRM,
	file: OutlineIcons.FILE,
	mail: OutlineIcons.MAIL,
	message: OutlineIcons.MESSAGE,
	phone_up: OutlineIcons.PHONE_UP,
	calendar_with_slots: OutlineIcons.CALENDAR_WITH_SLOTS,
	attach: OutlineIcons.ATTACH,
	location: OutlineIcons.LOCATION,
	person: OutlineIcons.PERSON,
	graduation_cap: OutlineIcons.GRADUATION_CAP,
	shopping_cart: OutlineIcons.SHOPPING_CART,
	wallet: OutlineIcons.WALLET,
	collab: OutlineIcons.COLLAB,
	developer_resources: OutlineIcons.DEVELOPER_RESOURCES,
	services: OutlineIcons.SERVICES,
	idea_lamp: OutlineIcons.IDEA_LAMP,
	gift: OutlineIcons.GIFT,
	cloud: OutlineIcons.CLOUD,
	notification: OutlineIcons.NOTIFICATION,
};
