<?

$aliases = array(
    array('Bitrix\BIConnector\Integration\Superset\Integrator\Integrator', 'Bitrix\BIConnector\Integration\Superset\Integrator\ProxyIntegrator'),
    array('Bitrix\BIConnector\Integration\Superset\Integrator\Sender', 'Bitrix\BIConnector\Integration\Superset\Integrator\ProxySender'),
    array('Bitrix\BIConnector\Integration\Superset\Integrator\ServiceLocation', 'Bitrix\BIConnector\Integration\Superset\Integrator\SupersetServiceLocation'),
    array('Bitrix\Bizproc\Workflow\Template\Entity\WorkflowTemplateTable', 'Bitrix\Bizproc\WorkflowTemplateTable'),
    array('Bitrix\Bizproc\Workflow\Entity\WorkflowInstanceTable', 'Bitrix\Bizproc\WorkflowInstanceTable'),
    array('Bitrix\Bizproc\Workflow\Entity\WorkflowStateTable', 'Bitrix\Bizproc\WorkflowStateTable'),
    array('CBPWorkflowPersister', 'CBPAllWorkflowPersister'),
    array('CBPHistoryService', 'CBPAllHistoryService'),
    array('CBPStateService', 'CBPAllStateService'),
    array('CBPTaskService', 'CBPAllTaskService'),
    array('CBPTrackingService', 'CBPAllTrackingService'),
    array('CBPWorkflowTemplateLoader', 'CAllBPWorkflowTemplateLoader'),
    array('Bitrix\Bizproc\Calc\Parser', 'CBPCalc'),
    array('Bitrix\Crm\Communication\Type', 'Bitrix\Crm\CommunicationType'),
    array('Bitrix\Crm\Order\Builder\OrderBuilderCrm', 'Bitrix\Crm\Order\OrderBuilderCrm'),
    array('Bitrix\Crm\Order\Builder\OrderBuilderRest', 'Bitrix\Crm\Order\OrderBuilderRest'),
    array('Bitrix\Crm\Order\Builder\BasketBuilderCrm', 'Bitrix\Crm\Order\BasketBuilderCrm'),
    array('Bitrix\Main\Composite\Helper', 'CHTMLPagesCache'),
    array('Bitrix\Main\ORM\Fields\IReadable', 'Bitrix\Main\Entity\Field\IReadable'),
    array('Bitrix\Main\ORM\Fields\IStorable', 'Bitrix\Main\Entity\Field\IStorable'),
    array('Bitrix\Main\ORM\Fields\BooleanField', 'Bitrix\Main\Entity\BooleanField'),
    array('Bitrix\Main\ORM\Fields\DateField', 'Bitrix\Main\Entity\DateField'),
    array('Bitrix\Main\ORM\Fields\DatetimeField', 'Bitrix\Main\Entity\DatetimeField'),
    array('Bitrix\Main\ORM\Fields\EnumField', 'Bitrix\Main\Entity\EnumField'),
    array('Bitrix\Main\ORM\Fields\ExpressionField', 'Bitrix\Main\Entity\ExpressionField'),
    array('Bitrix\Main\ORM\Fields\IntegerField', 'Bitrix\Main\Entity\IntegerField'),
    array('Bitrix\Main\ORM\Fields\FloatField', 'Bitrix\Main\Entity\FloatField'),
    array('Bitrix\Main\ORM\Fields\StringField', 'Bitrix\Main\Entity\StringField'),
    array('Bitrix\Main\ORM\Fields\TextField', 'Bitrix\Main\Entity\TextField'),
    array('Bitrix\Main\ORM\Fields\CryptoField', 'Bitrix\Main\Entity\CryptoField'),
    array('Bitrix\Main\ORM\Fields\Relations\Reference', 'Bitrix\Main\Entity\ReferenceField'),
    array('Bitrix\Main\ORM\Fields\ScalarField', 'Bitrix\Main\Entity\ScalarField'),
    array('Bitrix\Main\ORM\Fields\Field', 'Bitrix\Main\Entity\Field'),
    array('Bitrix\Main\ORM\Fields\FieldError', 'Bitrix\Main\Entity\FieldError'),
    array('Bitrix\Main\ORM\Fields\Validators\IValidator', 'Bitrix\Main\Entity\IValidator'),
    array('Bitrix\Main\ORM\Fields\Validators\Validator', 'Bitrix\Main\Entity\Validator\Base'),
    array('Bitrix\Main\ORM\Fields\Validators\DateValidator', 'Bitrix\Main\Entity\Validator\Date'),
    array('Bitrix\Main\ORM\Fields\Validators\EnumValidator', 'Bitrix\Main\Entity\Validator\Enum'),
    array('Bitrix\Main\ORM\Fields\Validators\ForeignValidator', 'Bitrix\Main\Entity\Validator\Foreign'),
    array('Bitrix\Main\ORM\Fields\Validators\LengthValidator', 'Bitrix\Main\Entity\Validator\Length'),
    array('Bitrix\Main\ORM\Fields\Validators\RangeValidator', 'Bitrix\Main\Entity\Validator\Range'),
    array('Bitrix\Main\ORM\Fields\Validators\RegExpValidator', 'Bitrix\Main\Entity\Validator\RegExp'),
    array('Bitrix\Main\ORM\Fields\Validators\UniqueValidator', 'Bitrix\Main\Entity\Validator\Unique'),
    array('Bitrix\Main\ORM\Query\INosqlPrimarySelector', 'Bitrix\Main\Entity\INosqlPrimarySelector'),
    array('Bitrix\Main\ORM\Query\NosqlPrimarySelector', 'Bitrix\Main\Entity\NosqlPrimarySelector'),
    array('Bitrix\Main\ORM\Query\Query', 'Bitrix\Main\Entity\Query'),
    array('Bitrix\Main\ORM\Query\Chain', 'Bitrix\Main\Entity\QueryChain'),
    array('Bitrix\Main\ORM\Query\ChainElement', 'Bitrix\Main\Entity\QueryChainElement'),
    array('Bitrix\Main\ORM\Query\Filter\Expressions\Expression', 'Bitrix\Main\Entity\Query\Filter\Expression\Base'),
    array('Bitrix\Main\ORM\Query\Filter\Expressions\ColumnExpression', 'Bitrix\Main\Entity\Query\Filter\Expression\Column'),
    array('Bitrix\Main\ORM\Query\Filter\Expressions\NullExpression', 'Bitrix\Main\Entity\Query\Filter\Expression\NullEx'),
    array('Bitrix\Main\ORM\Data\DataManager', 'Bitrix\Main\Entity\DataManager'),
    array('Bitrix\Main\ORM\Data\Result', 'Bitrix\Main\Entity\Result'),
    array('Bitrix\Main\ORM\Data\AddResult', 'Bitrix\Main\Entity\AddResult'),
    array('Bitrix\Main\ORM\Data\UpdateResult', 'Bitrix\Main\Entity\UpdateResult'),
    array('Bitrix\Main\ORM\Data\DeleteResult', 'Bitrix\Main\Entity\DeleteResult'),
    array('Bitrix\Main\ORM\Query\Filter\Condition', 'Bitrix\Main\Entity\Query\Filter\Condition'),
    array('Bitrix\Main\ORM\Query\Filter\ConditionTree', 'Bitrix\Main\Entity\Query\Filter\ConditionTree'),
    array('Bitrix\Main\ORM\Query\Filter\Helper', 'Bitrix\Main\Entity\Query\Filter\Helper'),
    array('Bitrix\Main\ORM\Query\Filter\Operator', 'Bitrix\Main\Entity\Query\Filter\Operator'),
    array('Bitrix\Main\ORM\Query\Expression', 'Bitrix\Main\Entity\Query\Expression'),
    array('Bitrix\Main\ORM\Query\Join', 'Bitrix\Main\Entity\Query\Join'),
    array('Bitrix\Main\ORM\Query\Union', 'Bitrix\Main\Entity\Query\Union'),
    array('Bitrix\Main\ORM\Query\UnionCondition', 'Bitrix\Main\Entity\Query\UnionCondition'),
    array('Bitrix\Main\ORM\Entity', 'Bitrix\Main\Entity\Base'),
    array('Bitrix\Main\ORM\EntityError', 'Bitrix\Main\Entity\EntityError'),
    array('Bitrix\Main\ORM\Event', 'Bitrix\Main\Entity\Event'),
    array('Bitrix\Main\ORM\EventResult', 'Bitrix\Main\Entity\EventResult'),
    array('Bitrix\Main\Entity\UField', 'Bitrix\Main\ORM\UField'),
    array('Bitrix\Main\Data\CacheEngineInterface', 'Bitrix\Main\Data\ICacheEngine'),
    array('Bitrix\Main\Data\CacheEngineStatInterface', 'Bitrix\Main\Data\ICacheEngineStat'),
    array('Bitrix\Main\Type\Collection', 'Bitrix\Main\Type\ArrayHelper'),
    array('Bitrix\Main\Composite\AppCache', 'Bitrix\Main\Data\AppCacheManifest'),
    array('Bitrix\Main\Composite\BufferArea', 'Bitrix\Main\Page\FrameBuffered'),
    array('Bitrix\Main\Composite\BufferArea', 'Bitrix\Main\Page\FrameHelper'),
    array('Bitrix\Main\Composite\Engine', 'Bitrix\Main\Page\Frame'),
    array('Bitrix\Main\Composite\Page', 'Bitrix\Main\Data\StaticHtmlCache'),
    array('Bitrix\Main\Composite\AbstractResponse', 'StaticHtmlCacheResponse'),
    array('Bitrix\Main\Composite\MemcachedResponse', 'StaticHtmlMemcachedResponse'),
    array('Bitrix\Main\Composite\FileResponse', 'StaticHtmlFileResponse'),
    array('Bitrix\Main\Composite\StaticArea', 'Bitrix\Main\Page\FrameStatic'),
    array('Bitrix\Main\Composite\Data\AbstractStorage', 'Bitrix\Main\Data\StaticHtmlStorage'),
    array('Bitrix\Main\Composite\Data\CacheProvider', 'Bitrix\Main\Data\StaticCacheProvider'),
    array('Bitrix\Main\Composite\Data\FileStorage', 'Bitrix\Main\Data\StaticHtmlFileStorage'),
    array('Bitrix\Main\Composite\Data\MemcachedStorage', 'Bitrix\Main\Data\StaticHtmlMemcachedStorage'),
    array('Bitrix\Pull\Model\ChannelTable', 'Bitrix\Pull\ChannelTable'),
    array('Bitrix\Pull\Model\PushTable', 'Bitrix\Pull\PushTable'),
    array('Bitrix\Sale\TradingPlatform\YMarket\YandexMarket', 'Bitrix\Sale\TradingPlatform\YandexMarket'),
    array('Bitrix\Sale\PaySystem\Logger', 'Bitrix\Sale\PaySystem\ErrorLog'),
    array('Bitrix\Sale\Internals\OrderTable', 'Bitrix\Sale\OrderTable'),
    array('Bitrix\Sale\Internals\FuserTable', 'Bitrix\Sale\FuserTable'),
    array('Bitrix\Sale\Internals\Product2ProductTable', 'Bitrix\Sale\Product2ProductTable'),
    array('Bitrix\Sale\Internals\StoreProductTable', 'Bitrix\Sale\StoreProductTable'),
    array('Bitrix\Sale\Internals\PersonTypeTable', 'Bitrix\Sale\PersonTypeTable'),
    array('Bitrix\Sale\Internals\ProductTable', 'Bitrix\Sale\ProductTable'),
    array('Bitrix\Sale\Internals\SectionTable', 'Bitrix\Sale\SectionTable'),
    array('Bitrix\Sale\Internals\OrderProcessingTable', 'Bitrix\Sale\OrderProcessingTable'),
    array('Bitrix\Sale\Internals\GoodsSectionTable', 'Bitrix\Sale\GoodsSectionTable'),
    array('Bitrix\Sale\Delivery\Restrictions\ByPersonType', 'Bitrix\Sale\Delivery\Restrictions\PersonType'),
    array('Bitrix\Sender\Connector\Base', 'Bitrix\Sender\Connector'),
    array('Bitrix\Sender\Connector\Manager', 'Bitrix\Sender\ConnectorManager'),
    array('Bitrix\Sender\Connector\Result', 'Bitrix\Sender\ConnectorResult'),
    array('Bitrix\Sender\Trigger\Base', 'Bitrix\Sender\Trigger'),
    array('Bitrix\Sender\Trigger\Manager', 'Bitrix\Sender\TriggerManager'),
    array('Bitrix\Sender\Trigger\Settings', 'Bitrix\Sender\TriggerSettings'),
    array('Bitrix\Sender\Trigger\TriggerConnector', 'Bitrix\Sender\TriggerConnector'),
    array('Bitrix\Sender\Trigger\TriggerConnectorClosed', 'Bitrix\Sender\TriggerConnectorClosed'),
    array('Bitrix\Seo\Sitemap\Internals\SitemapTable', 'Bitrix\Seo\SitemapTable'),
    array('Bitrix\Seo\Sitemap\Internals\EntityTable', 'Bitrix\Seo\SitemapEntityTable'),
    array('Bitrix\Seo\Sitemap\Internals\ForumTable', 'Bitrix\Seo\SitemapForumTable'),
    array('Bitrix\Seo\Sitemap\Internals\IblockTable', 'Bitrix\Seo\SitemapIblockTable'),
    array('Bitrix\Seo\Sitemap\Internals\RuntimeTable', 'Bitrix\Seo\SitemapRuntimeTable'),
    array('Bitrix\Seo\Sitemap\Source\Forum', 'Bitrix\Seo\SitemapForum'),
    array('Bitrix\Seo\Sitemap\Source\Iblock', 'Bitrix\Seo\SitemapIblock'),
    array('Bitrix\Seo\Sitemap\File\Base', 'Bitrix\Seo\SitemapFile'),
    array('Bitrix\Seo\Sitemap\File\Index', 'Bitrix\Seo\SitemapIndex'),
    array('Bitrix\Seo\Sitemap\File\Runtime', 'Bitrix\Seo\SitemapRuntime'),
    array('Bitrix\Tasks\Internals\DataBase\Helper\Common', 'Bitrix\Tasks\DB\CommonHelper'),
    array('Bitrix\Tasks\Internals\DataBase\Helper', 'Bitrix\Tasks\DB\Helper'),
    array('Bitrix\Tasks\Internals\DataBase\Tree', 'Bitrix\Tasks\DB\Tree'),
    array('Bitrix\Tasks\Internals\DataBase\Mesh', 'Bitrix\Tasks\DB\Mesh'),
    array('Bitrix\Tasks\Internals\DataBase\Tree\NodeNotFoundException', 'Bitrix\Tasks\DB\Tree\NodeNotFoundException'),
    array('Bitrix\Tasks\Internals\DataBase\Tree\TargetNodeNotFoundException', 'Bitrix\Tasks\DB\Tree\TargetNodeNotFoundException'),
    array('Bitrix\Tasks\Internals\DataBase\Tree\ParentNodeNotFoundException', 'Bitrix\Tasks\DB\Tree\ParentNodeNotFoundException'),
    array('Bitrix\Tasks\Internals\DataBase\Tree\LinkExistsException', 'Bitrix\Tasks\DB\Tree\LinkExistsException'),
    array('Bitrix\Tasks\Internals\DataBase\Tree\LinkNotExistException', 'Bitrix\Tasks\DB\Tree\LinkNotExistException'),
    array('Bitrix\Tasks\Integration\Report\Internals\TaskTable', 'Bitrix\Tasks\TaskTable'),
    array('Bitrix\Tasks\Internals\Task\LabelTable', 'Bitrix\Tasks\TagTable'),
    array('Bitrix\Tasks\Internals\Task\LabelTable', 'Bitrix\Tasks\Task\TagTable'),
    array('Bitrix\Tasks\Internals\Task\MemberTable', 'Bitrix\Tasks\MemberTable'),
    array('Bitrix\Tasks\Internals\Task\ElapsedTimeTable', 'Bitrix\Tasks\ElapsedTimeTable'),
    array('Bitrix\Tasks\Internals\Task\SortingTable', 'Bitrix\Tasks\Task\SortingTable'),
    array('Bitrix\Tasks\Internals\Task\FavoriteTable', 'Bitrix\Tasks\Task\FavoriteTable'),
    array('Bitrix\Tasks\Internals\Task\ProjectDependenceTable', 'Bitrix\Tasks\Task\DependenceTable'),
    array('Bitrix\Tasks\Internals\Task\TemplateTable', 'Bitrix\Tasks\TemplateTable'),
    array('Bitrix\Tasks\Internals\Task\Template\DependenceTable', 'Bitrix\Tasks\Template\DependencyTable'),
    array('Bitrix\Tasks\Internals\Task\Template\CheckListTable', 'Bitrix\Tasks\Template\CheckListTable'),
    array('Bitrix\Tasks\Internals\Task\Template\CheckListTable', 'Bitrix\Tasks\Template\CheckListItemTable'),
    array('Bitrix\Tasks\Internals\Notification\Task\ThrottleTable', 'Bitrix\Tasks\Notification\ThrottleTable'),
    array('Bitrix\Tasks\UI', 'Bitrix\Tasks\Util\UI'),
    array('Bitrix\Tasks\Internals\Log\LogFacade', 'Bitrix\Tasks\Internals\Log\Logger'),
    array('Bitrix\Baas\Entity\Service', 'Bitrix\Baas\Service'),
    array('Bitrix\Baas\Controller\ServerPort\Lead', 'Bitrix\Baas\Controller\ServerPort\Domain'),
    array('Bitrix\Iblock\IblockSiteTable', 'Bitrix\Iblock\SiteTable'),
    array('Bitrix\Tasks\Integration\Integration', 'Bitrix\Tasks\Integration'),
    array('Bitrix\Tasks\Util\Util', 'Bitrix\Tasks\Util'),
    array('Bitrix\Tasks\Util\UI', 'Bitrix\Tasks\UI'),
    array('Bitrix\Tasks\Provider\Query\TaskQuery', 'Bitrix\Tasks\Provider\TaskQuery'),
    array('Bitrix\Tasks\V2\Internal\Service\Task\Action\Add\Async\Message\AddLastActivity', 'Bitrix\Tasks\V2\Internals\Control\Task\Action\Add\Async\Message\AddLastActivity'),
    array('Bitrix\Tasks\V2\Internal\Service\Task\Action\Add\Async\Message\AddDavSync', 'Bitrix\Tasks\V2\Internals\Control\Task\Action\Add\Async\Message\AddDavSync'),
    array('Bitrix\Tasks\V2\Internal\Service\Task\Action\Add\Async\Message\AddScenario', 'Bitrix\Tasks\V2\Internals\Control\Task\Action\Add\Async\Message\AddScenario'),
    array('Bitrix\Tasks\V2\Internal\Service\Task\Action\Add\Async\Message\AddSearchIndex', 'Bitrix\Tasks\V2\Internals\Control\Task\Action\Add\Async\Message\AddSearchIndex'),
    array('Bitrix\Tasks\V2\Internal\Service\Task\Action\Add\Async\Receiver\AddLastActivity', 'Bitrix\Tasks\V2\Internals\Control\Task\Action\Add\Async\Receiver\AddLastActivity'),
    array('Bitrix\Tasks\V2\Internal\Service\Task\Action\Add\Async\Receiver\AddDavSync', 'Bitrix\Tasks\V2\Internals\Control\Task\Action\Add\Async\Receiver\AddDavSync'),
    array('Bitrix\Tasks\V2\Internal\Service\Task\Action\Add\Async\Receiver\AddScenario', 'Bitrix\Tasks\V2\Internals\Control\Task\Action\Add\Async\Receiver\AddScenario'),
    array('Bitrix\Tasks\V2\Internal\Service\Task\Action\Add\Async\Receiver\AddSearchIndex', 'Bitrix\Tasks\V2\Internals\Control\Task\Action\Add\Async\Receiver\AddSearchIndex'),
);

$description = "";
foreach ($aliases as $alias) {
    $className = $alias["1"];
    $aliasName = $alias["0"];

    $classParts = explode("\\", $className);
    $class = array_pop($classParts);

    if (count($classParts) > 0)
        $description .= "namespace " . implode("\\", $classParts) . " {" . PHP_EOL;
    else
        $description .= "namespace {" . PHP_EOL;

    $description .= "class " . $class . " extends \\" . $aliasName . " {}" . PHP_EOL;

    $description .= "}" . PHP_EOL;

    $description .= PHP_EOL;
}

print_r($description);
