<?php

return [
	'extensions' => [
		'assets/icons',
		'layout/ui/menu',
		'layout/ui/safe-image',
		'tokens',
		'type',
		'ui-system/blocks/icon',
		'ui-system/typography/text',
		'utils/function',
		'utils/object',
		'utils/random',
		'utils/skeleton',
		'im:messenger/const',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/feature',
		'im:messenger/lib/helper',
		'im:messenger/lib/logger',
		'im:messenger/lib/rest',
		'im:messenger/lib/ui/notification',
		'im:messenger/loc',
		'im:messenger/provider/rest',
	],
	'bundle' => [
		'./src/const',
		'./src/manager',
		'./src/pack-viewer',
		'./src/selector',
		'./src/service',
		'./src/ui/grid/grid',
		'./src/ui/grid/rows/pack-header',
		'./src/ui/grid/rows/shimmer-header',
		'./src/ui/grid/rows/shimmer-stickers',
		'./src/ui/grid/rows/stickers',
		'./src/ui/menu/pack',
		'./src/ui/menu/sticker',
		'./src/ui/navigation/bar',
		'./src/ui/navigation/buttons/active-indicator',
		'./src/ui/navigation/buttons/pack',
		'./src/ui/navigation/buttons/recent',
		'./src/ui/navigation/buttons/shimmer',
		'./src/utils/emitter',
		'./src/utils/grid',
	],
];
