<?php
if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	die();
}

return [
	'css' => 'dist/messenger.bundle.css',
	'js' => 'dist/messenger.bundle.js',
	'rel' => [
		'im.integration.viewer',
		'im.public',
		'im.v2.application.core',
		'im.v2.component.content.chat',
		'im.v2.component.content.chat-forms.forms',
		'im.v2.component.content.folder-forms',
		'im.v2.component.content.market',
		'im.v2.component.content.notification',
		'im.v2.component.content.openlines',
		'im.v2.component.content.openlinesV2',
		'im.v2.component.content.settings',
		'im.v2.component.desktop.mode-selection-banner',
		'im.v2.component.list.container.ai-assistant',
		'im.v2.component.list.container.channel',
		'im.v2.component.list.container.collab',
		'im.v2.component.list.container.folder',
		'im.v2.component.list.container.openline',
		'im.v2.component.list.container.recent',
		'im.v2.component.list.container.task',
		'im.v2.component.list.navigator',
		'im.v2.const',
		'im.v2.css.classes',
		'im.v2.css.icons',
		'im.v2.css.tokens',
		'im.v2.lib.analytics',
		'im.v2.lib.bulk-actions',
		'im.v2.lib.counter',
		'im.v2.lib.desktop',
		'im.v2.lib.desktop-api',
		'im.v2.lib.esc-manager',
		'im.v2.lib.feature',
		'im.v2.lib.folder',
		'im.v2.lib.init',
		'im.v2.lib.layout',
		'im.v2.lib.logger',
		'im.v2.lib.menu',
		'im.v2.lib.page-context',
		'im.v2.lib.promo',
		'im.v2.lib.theme',
		'im.v2.provider.service.folder',
		'main.core',
		'main.core.events',
		'main.sidepanel',
		'planner',
		'ui.design-tokens',
		'ui.fontawesome4',
		'ui.fonts.opensans',
		'ui.icon-set.api.vue',
		'ui.sidepanel.layout',
		'ui.system.menu',
		'ui.vue3.components.button',
	],
	'skip_core' => false,
	'settings' => [
		'isLinesOperator' => \Bitrix\Im\Integration\Imopenlines\User::isOperator(),
	]
];
