<?php

return [
	'extensions' => [
		'assets/icons',
		'layout/ui/feedback-form-opener',
		'loc',
		'rest/run-action-executor',
		'settings-v2/const',
		'settings-v2/emitter',
		'settings-v2/controller/application-storage',
		'settings-v2/controller/native',
		'settings-v2/controller/push-config',
		'settings-v2/controller/notification-counter',
		'settings-v2/controller/push-status',
		'settings-v2/controller/smartfilter-status',
		'settings-v2/controller/cache',
		'settings-v2/services/native',
		'settings-v2/services/notification-load',
		'settings-v2/services/developer-settings-cache',
		'settings-v2/services/db/messenger',
		'utils/object',
		'type',
		'utils/copy',
		'toast',
		'tokens',
		'feature-flag',
		'alert',
		'feature',
		'qrauth/utils',
		'settings-v2/controller/security',
		'settings-v2/services/security-load',
		'settings-v2/services/security-settings',
		'settings-v2/services/assets-preload',
	],
	'bundle' => [
		'./pages/debug',
		'./pages/messenger',
		'./pages/root',
		'./pages/theme',
		'./pages/sync',
		'./pages/security',
		'./pages/video-quality',
		'./pages/memory',
		'./pages/notifications/root',
		'./pages/notifications/module',
		'./pages/notifications/counter',
		'./pages/notifications/push',
		'./pages/developer',

		'./helpers/item-create-helper',
		'./helpers/cache-item-create-helper',
		'./helpers/assert',
		'./helpers/security-item-create-helper',
	],
];
