/**
 * @module im/messenger/loc/src/feature-phrases
 */
jn.define('im/messenger/loc/src/feature-phrases', (require, exports, module) => {
	const { Feature } = require('im/messenger/lib/feature');

	/**
	 * @typedef {string} NewPhraseCode
	 * @typedef {string} LegacyPhraseCode
	 */

	/**
	 * @typedef FeaturePhraseGroup
	 * @property {() => boolean} isFeatureEnabled
	 * @property {Record<NewPhraseCode, LegacyPhraseCode>} phrases
	 */
	/** @type {Array<FeaturePhraseGroup>} */
	const featurePhrases = [
		{
			isFeatureEnabled: () => Feature.isNestedChatAvailable,
			phrases: {
				IMMOBILE_RECENT_SERVICE_EMPTY_STATE_PROJECT_TITLE: 'IMMOBILE_RECENT_SERVICE_EMPTY_STATE_COLLAB_TITLE',
				IMMOBILE_RECENT_SERVICE_EMPTY_STATE_PROJECT_TEXT: 'IMMOBILE_RECENT_SERVICE_EMPTY_STATE_COLLAB_TEXT',
				IMMOBILE_MESSENGER_PROVIDER_SERVICES_RECENT_ERROR_MAX_PINNED_V2: 'IMMOBILE_MESSENGER_PROVIDER_SERVICES_RECENT_ERROR_MAX_PINNED',
				IMMOBILE_DIALOG_SIDEBAR_PROJECT_DESCRIPTION: 'IMMOBILE_DIALOG_SIDEBAR_COLLAB_DESCRIPTION',
				IMMOBILE_DIALOG_SIDEBAR_WIDGET_TITLE_PROJECT: 'IMMOBILE_DIALOG_SIDEBAR_WIDGET_TITLE_COLLAB',
				IMMOBILE_DIALOG_SIDEBAR_PROJECT_ERROR_DELETE_PROJECT: 'IMMOBILE_DIALOG_SIDEBAR_COLLAB_ERROR_DELETE_COLLAB',
				IMMOBILE_DIALOG_SIDEBAR_PROJECT_DELETE_ERROR: 'IMMOBILE_DIALOG_SIDEBAR_COLLAB_DELETE_ERROR',
				IMMOBILE_PARTICIPANTS_MANAGER_ITEM_LIST_REMOVE_FROM_PROJECT: 'IMMOBILE_PARTICIPANTS_MANAGER_ITEM_LIST_REMOVE_FROM_COLLAB',
				IMMOBILE_SIDEBAR_V2_PARTICIPANTS_MENU_ITEM_LIST_REMOVE_FROM_PROJECT: 'IMMOBILE_SIDEBAR_V2_PARTICIPANTS_MENU_ITEM_LIST_REMOVE_FROM_COLLAB',
				IMMOBILE_SIDEBAR_V2_COMMON_PROJECT_TITLE: 'IMMOBILE_SIDEBAR_V2_COMMON_COLLAB_TITLE',
				IMMOBILE_SIDEBAR_V2_COMMON_PROJECT_DELETE_ERROR_NOT_EMPTY: 'IMMOBILE_SIDEBAR_V2_COMMON_COLLAB_DELETE_ERROR_NOT_EMPTY',
				IMMOBILE_SIDEBAR_V2_COMMON_PROJECT_DELETE_ERROR_DEFAULT: 'IMMOBILE_SIDEBAR_V2_COMMON_COLLAB_DELETE_ERROR_DEFAULT',
				IMMOBILE_DIALOG_CREATOR_NEW_PROJECT: 'IMMOBILE_DIALOG_CREATOR_NEW_COLLAB',
				IMMOBILE_MESSENGER_CONTROLLER_RECENT_SERVICE_ACTION_PIN_ERROR_MAX_PINNED_V2: 'IMMOBILE_MESSENGER_CONTROLLER_RECENT_SERVICE_ACTION_PIN_ERROR_MAX_PINNED',
				IMMOBILE_MESSENGER_UI_NOTIFY_TOAST_DELETE_PROJECT: 'IMMOBILE_MESSENGER_UI_NOTIFY_TOAST_DELETE_COLLAB',
				IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_DELETE_PROJECT_TITLE: 'IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_DELETE_COLLAB_TITLE',
				IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_DELETE_PROJECT_DESCRIPTION: 'IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_DELETE_COLLAB_DESCRIPTION',
				IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_LEAVE_PROJECT_TITLE: 'IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_LEAVE_COLLAB_TITLE',
				IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_LEAVE_PROJECT_DESCRIPTION: 'IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_LEAVE_COLLAB_DESCRIPTION',
				IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_REMOVE_PROJECT_TITLE: 'IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_REMOVE_COLLAB_TITLE',
				IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_REMOVE_PROJECT_DESCRIPTION: 'IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_REMOVE_COLLAB_DESCRIPTION',
				IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_CLEAR_HISTORY_PROJECT_TITLE: 'IMMOBILE_MESSENGER_UI_NOTIFY_ALERT_CLEAR_HISTORY_COLLAB_TITLE',
				IMMOBILE_ELEMENT_CHAT_TITLE_PROJECT: 'IMMOBILE_ELEMENT_CHAT_TITLE_COLLAB',
				IMMOBILE_MESSAGE_SIGN_INVITE_B2B_DOCUMENT_SIGNING_DESCRIPTION_V2: 'IMMOBILE_MESSAGE_SIGN_INVITE_B2B_DOCUMENT_SIGNING_DESCRIPTION',
				IMMOBILE_MESSAGE_SIGN_DONE_B2B_DOCUMENT_SIGNING_DESCRIPTION_V2: 'IMMOBILE_MESSAGE_SIGN_DONE_B2B_DOCUMENT_SIGNING_DESCRIPTION',
				IMMOBILE_FOLDER_LIST_SYSTEM_DESCRIPTION_PROJECT: 'IMMOBILE_FOLDER_LIST_SYSTEM_DESCRIPTION_COLLAB',
			}
		}
	]
	
	module.exports = { featurePhrases };
});
