<?php

return [
	'extensions' => [
		'asset-manager',
		'assets/icons',
		'elements-stack',
		'im:messenger/api/dialog-opener',
		'layout/ui/friendly-date',
		'layout/ui/friendly-date/formatter-factory',
		'layout/ui/gratitude-list',
		'loc',
		'statemanager/redux/batched-actions',
		'statemanager/redux/connect',
		'statemanager/redux/slices/gratitude',
		'statemanager/redux/slices/users',
		'statemanager/redux/store',
		'tokens',
		'type',
		'ui-system/blocks/avatar',
		'ui-system/blocks/icon',
		'ui-system/form/buttons/button',
		'ui-system/layout/area',
		'ui-system/layout/area-list',
		'ui-system/layout/box',
		'ui-system/typography/bbcodetext',
		'ui-system/typography/heading',
		'ui-system/typography/text',
		'user-profile/api',
		'utils/date',
		'utils/enums/base',
		'utils/skeleton',
		'utils/test',
	],
	'bundle' => [
		'./src/block/gratitude',
		'./src/block/header',
		'./src/enum/user-status',
		'./src/profile-card',
	],
];
