<?php

return [
	'extensions' => [
		'type',
		'native/memorystore',
		'utils/uuid',
		'im:messenger/const',
		'im:messenger/controller/messenger-header',
		'im:messenger/controller/recent/manager',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/logger',
		'im:messenger/lib/params',
		'im:messenger/lib/utils',
		'im:messenger/provider/services/analytics',
		'im:messenger/lib/wait-view-loaded',
		'im:messenger/loc',
		'im:messenger/controller/recent/manager',
		'im:messenger/lib/counters/tab-counters',
		'im:messenger/provider/services/chat',
		'im:messenger/lib/element/chat-avatar',
		'im:messenger/lib/popup-menu/recent-actions',
		'im:messenger/controller/folder/list',
	],
	'bundle' => [
		'./src/api-handler',
		'./src/helper',
		'./src/manager',
		'./src/folder-tabs-controller',
		'./src/result',
		'./src/tab-switcher',
		'./src/nested/tab-switcher',
		'./src/nested/opener',
		'./src/nested/context',
		'./src/nested/mutation-handler',
		'./src/nested/tabs-config',
	],
];
