<?php

return [
	'extensions' => [
		'native/memorystore',
		'type',
		'ui-system/blocks/icon',
		'utils/uuid',
		'im:messenger/const',
		'im:messenger/controller/folder/list',
		'im:messenger/lib/counters/tab-counters',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/element/chat-avatar',
		'im:messenger/lib/feature',
		'im:messenger/lib/logger',
		'im:messenger/lib/params',
		'im:messenger/lib/plan-limit',
		'im:messenger/lib/popup-menu/recent-actions',
		'im:messenger/lib/ui/notification',
		'im:messenger/lib/utils',
		'im:messenger/lib/wait-view-loaded',
		'im:messenger/loc',
		'im:messenger/provider/services/analytics',
		'im:messenger/provider/services/chat',
	],
	'bundle' => [
		'./src/api-handler',
		'./src/helper',
		'./src/manager',
		'./src/folder-tabs-controller',
		'./src/result',
		'./src/tab-switcher',
		'./src/nested/tab-switcher',
		'./src/nested/opener',
		'./src/nested/context',
		'./src/nested/mutation-handler',
		'./src/nested/deletion-watcher',
		'./src/nested/tabs-config',
		'./src/nested/open-filter/base',
		'./src/nested/open-filter/projects-tariff-restriction',
	],
];
