CREATE TABLE IF NOT EXISTS b_note_collection (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	CREATED_BY INT NOT NULL,
	POSITION INT NOT NULL DEFAULT 0,
	POLICY_LEVEL INT NOT NULL DEFAULT 0,
	IS_ARCHIVED CHAR(1) NOT NULL DEFAULT 'N',
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY INT NOT NULL,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	INDEX IX_NOTE_COLL_SORT (IS_ARCHIVED, POSITION, ID)
);

CREATE TABLE IF NOT EXISTS b_note_document (
	ID INT NOT NULL AUTO_INCREMENT,
	COLLECTION_ID INT NOT NULL,
	PARENT_ID INT NULL,
	TITLE VARCHAR(255) NOT NULL,
	MARKDOWN MEDIUMTEXT NOT NULL,
	YJS_STATE MEDIUMTEXT DEFAULT NULL,
	CONTENT_FORMAT VARCHAR(5) NOT NULL DEFAULT 'yjs',
	POSITION INT NOT NULL DEFAULT 0,
	IS_ARCHIVED CHAR(1) NOT NULL DEFAULT 'N',
	ARCHIVED_AT DATETIME NULL,
	ARCHIVED_BY INT NULL,
	CREATED_BY INT NOT NULL,
	UPDATED_BY INT NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	INDEX IX_NOTE_DOC_BRANCH (COLLECTION_ID, PARENT_ID, IS_ARCHIVED, POSITION, ID),
	INDEX IX_NOTE_DOC_BRANCH_REORDER (COLLECTION_ID, PARENT_ID, POSITION),
	INDEX IX_NOTE_DOC_ARCHIVE (IS_ARCHIVED, ARCHIVED_AT, ID)
);

CREATE TABLE IF NOT EXISTS b_note_document_file (
	DOCUMENT_ID INT NOT NULL,
	FILE_ID INT NOT NULL,
	CREATED_BY INT NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (DOCUMENT_ID, FILE_ID),
	UNIQUE INDEX IX_NOTE_DOC_FILE_UNIQ_FILE (FILE_ID)
);

CREATE TABLE IF NOT EXISTS b_note_role
(
	ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(250) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_note_role_relation
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_ID INT UNSIGNED NOT NULL,
	RELATION VARCHAR(8) NOT NULL DEFAULT '',
	PRIMARY KEY (ID),
	INDEX IX_NOTE_ROLE_REL (ROLE_ID, RELATION)
);

CREATE TABLE IF NOT EXISTS b_note_permission
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_ID INT UNSIGNED NOT NULL,
	PERMISSION_ID VARCHAR(32) NOT NULL DEFAULT '0',
	VALUE INT NOT NULL DEFAULT '0',
	PRIMARY KEY (ID),
	INDEX IX_NOTE_PERM (ROLE_ID, PERMISSION_ID, VALUE)
);

CREATE TABLE IF NOT EXISTS b_note_collection_access
(
	ID INT NOT NULL AUTO_INCREMENT,
	COLLECTION_ID INT NOT NULL,
	SUBJECT_CODE VARCHAR(50) NOT NULL,
	LEVEL INT NOT NULL,
	CREATED_BY INT NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	UNIQUE INDEX IX_NOTE_COLLECTION_ACCESS_UNIQ (COLLECTION_ID, SUBJECT_CODE),
	INDEX IX_NOTE_COLL_ACCESS_SUBJECT (SUBJECT_CODE, COLLECTION_ID, LEVEL)
);

CREATE TABLE IF NOT EXISTS b_note_document_access
(
	ID INT NOT NULL AUTO_INCREMENT,
	DOCUMENT_ID INT NOT NULL,
	SUBJECT_CODE VARCHAR(50) NOT NULL,
	LEVEL INT NOT NULL,
	CREATED_BY INT NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	UNIQUE INDEX IX_NOTE_DOCUMENT_ACCESS_UNIQ (DOCUMENT_ID, SUBJECT_CODE),
	INDEX IX_NOTE_DOC_ACCESS_SUBJECT (SUBJECT_CODE, DOCUMENT_ID, LEVEL)
);

CREATE TABLE IF NOT EXISTS b_note_import_session (
	ID INT NOT NULL AUTO_INCREMENT,
	CREATED_BY INT NOT NULL,
	STATUS VARCHAR(32) NOT NULL DEFAULT 'connecting',
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_note_import_map (
	ID INT NOT NULL AUTO_INCREMENT,
	SOURCE_TYPE VARCHAR(32) NOT NULL,
	EXTERNAL_ID VARCHAR(128) NOT NULL,
	URL_ID VARCHAR(16) NULL DEFAULT NULL,
	DOCUMENT_ID INT NULL,
	COLLECTION_ID INT NULL,
	PRIMARY KEY (ID),
	UNIQUE INDEX UX_IMPORT_MAP (SOURCE_TYPE, EXTERNAL_ID),
	INDEX IX_IMPORT_MAP_URL_ID (SOURCE_TYPE, URL_ID)
);

CREATE TABLE IF NOT EXISTS b_note_unresolved_mention (
	ID INT NOT NULL AUTO_INCREMENT,
	DOCUMENT_ID INT NOT NULL,
	SOURCE_TYPE VARCHAR(32) NOT NULL,
	EXTERNAL_ID VARCHAR(128) NOT NULL,
	PRIMARY KEY (ID),
	INDEX IX_UNRESOLVED (SOURCE_TYPE, EXTERNAL_ID),
	INDEX IX_UNRESOLV_DOC (DOCUMENT_ID)
);

CREATE TABLE IF NOT EXISTS b_note_document_updates (
	ID INT NOT NULL AUTO_INCREMENT,
	DOCUMENT_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	PATCH MEDIUMTEXT NOT NULL,
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	INDEX IX_NOTE_DOC_UPD_DOCID (DOCUMENT_ID, ID)
);

CREATE TABLE IF NOT EXISTS b_note_document_search (
	ID INT NOT NULL AUTO_INCREMENT,
	DOCUMENT_ID INT NOT NULL,
	BODY MEDIUMTEXT NOT NULL,
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
	UNIQUE INDEX UX_NOTE_DOCUMENT_SEARCH_DOCUMENT (DOCUMENT_ID),
	FULLTEXT INDEX FT_NOTE_DOCUMENT_SEARCH_BODY (BODY)
);

CREATE TABLE IF NOT EXISTS b_note_recycle_bin (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	DOCUMENT_ID INT NOT NULL,
	TRASHED_AT DATETIME NOT NULL,
	TRASHED_BY INT NOT NULL,
	ORIGIN VARCHAR(40) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE INDEX UX_NOTE_RECYCLEBIN_DOC (DOCUMENT_ID),
	INDEX IX_NOTE_RECYCLEBIN_AT_ID (TRASHED_AT, ID),
	INDEX IX_NOTE_RECYCLEBIN_BY (TRASHED_BY)
);
