<?php

return [
	'extensions' => [
		'log',
		'type',
		'utils/object',
		'utils/string',
		'im:messenger/const',
		'im:messenger/loc',
		'im:messenger/lib/date-formatter',
		'im:messenger/lib/logger',
		'im:messenger/lib/params',
		'im:messenger/lib/smile-manager',
		'im:messenger/lib/di/service-locator',
		'im:messenger/lib/helper',
	],
	'bundle' => [
		'./src/parser',
		'./src/functions/action',
		'./src/functions/call',
		'./src/functions/common',
		'./src/functions/context',
		'./src/functions/date',
		'./src/functions/disk',
		'./src/functions/emoji',
		'./src/functions/font',
		'./src/functions/image',
		'./src/functions/lines',
		'./src/functions/mention',
		'./src/functions/quote',
		'./src/functions/slash-command',
		'./src/functions/smile',
		'./src/functions/url',
		'./src/utils/parsed-elements',
		'./src/utils/utils',
		'./src/elements/dialog/message/code',
		'./src/elements/dialog/message/quote-active',
		'./src/elements/dialog/message/quote-inactive',
		'./src/elements/dialog/message/text',
	],
];
