<?php

if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	die();
}

return [
	'css' => 'dist/chart.bundle.css',
	'js' => 'dist/chart.bundle.js',
	'rel' => [
		'bizproc.automation',
		'bizproc.dataview',
		'bizproc.router',
		'bizprocdesigner.editor.ai-assistant-widget-settings',
		'bizprocdesigner.feature',
		'disk.uploader.user-field-widget',
		'main.core',
		'main.core.events',
		'main.core.z-index-manager',
		'main.date',
		'main.popup',
		'pull.client',
		'ui.a11y',
		'ui.banner-dispatcher',
		'ui.bbcode.formatter.html-formatter',
		'ui.block-diagram',
		'ui.buttons',
		'ui.date-picker',
		'ui.design-tokens',
		'ui.dialogs.messagebox',
		'ui.draganddrop.draggable',
		'ui.entity-selector',
		'ui.feedback.form',
		'ui.icon-set.animated',
		'ui.icon-set.api.core',
		'ui.icon-set.api.vue',
		'ui.icon-set.outline',
		'ui.info-helper',
		'ui.loader',
		'ui.notification',
		'ui.progressround',
		'ui.system.alert',
		'ui.system.alert.vue',
		'ui.system.checkbox',
		'ui.system.chip.vue',
		'ui.system.dialog',
		'ui.system.input',
		'ui.system.input.vue',
		'ui.system.menu.vue',
		'ui.system.skeleton.vue',
		'ui.system.typography.vue',
		'ui.text-editor',
		'ui.tour',
		'ui.uploader.vue',
		'ui.vue3',
		'ui.vue3.components.button',
		'ui.vue3.components.menu',
		'ui.vue3.components.popup',
		'ui.vue3.directives.hint',
		'ui.vue3.pinia',
		'window',
	],
	'skip_core' => false,
];
