CREATE TABLE IF NOT EXISTS `b_hr_structure_node_backward_access_code`
(
	`ID` bigint NOT NULL AUTO_INCREMENT,
	`NODE_ID` bigint NOT NULL,
	`ACCESS_CODE` varchar(255) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX UX_B_HR_STRUCTURE_NODE_BACKWARD_ACCESS_CODE_ACCESS_CODE (`ACCESS_CODE`)
);

CREATE INDEX IX_B_HR_STRUCTURE_NODE_BACKWARD_ACCESS_CODE_NODE_ID
	ON b_hr_structure_node_backward_access_code (NODE_ID);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node_member_role`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`MEMBER_ID` bigint NOT NULL,
	`ROLE_ID` bigint NOT NULL,
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IX_B_HR_STRUCTURE_NODE_MEMBER_ROLE_MEMBER_ID
	ON b_hr_structure_node_member_role (MEMBER_ID);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node_member`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`ENTITY_TYPE` varchar(50) NOT NULL DEFAULT 'USER',
	`ENTITY_ID` bigint NOT NULL,
	`ACTIVE` varchar(1) default 'Y',
	`NODE_ID` bigint NOT NULL,
	`ADDED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE INDEX UX_B_HR_NODE_MEMBER_NODE_ID_ENTITY_TYPE_ENTITY_ID (`NODE_ID`, `ENTITY_TYPE`, `ENTITY_ID`)
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node_relation`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`NODE_ID` bigint NOT NULL,
	`ENTITY_ID` bigint NOT NULL,
	`ENTITY_TYPE` varchar(50) NOT NULL,
	`WITH_CHILD_NODES` varchar(1) default 'N',
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX B_HR_STRUCTURE_NODE_RELATION_IX
	ON b_hr_structure_node_relation (NODE_ID, ENTITY_TYPE, ENTITY_ID, WITH_CHILD_NODES);

CREATE INDEX B_HR_STRUCTURE_NODE_RELATION_ENTITY_TYPE_ENTITY_ID_IX
	ON b_hr_structure_node_relation (ENTITY_TYPE, ENTITY_ID);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node_role`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`NODE_ID` bigint NOT NULL,
	`ROLE_ID` bigint NOT NULL,
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `b_hr_structure`
(
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`NAME` varchar(255) NOT NULL,
	`TYPE` varchar(50) NOT NULL DEFAULT 'DEFAULT',
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`XML_ID` varchar(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_node` (
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`NAME` varchar(255) NOT NULL,
	`TYPE` varchar(50) NOT NULL,
	`STRUCTURE_ID` bigint NOT NULL,
	`PARENT_ID` bigint,
	`CREATED_BY` bigint NOT NULL,
	`CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	`UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`XML_ID` varchar(255)
);

CREATE INDEX B_HR_STRUCTURE_NODE_XML_ID_IX
	ON b_hr_structure_node (XML_ID);

CREATE INDEX IX_B_HR_STRUCTURE_NODE_STRUCTURE_ID
	ON b_hr_structure_node (STRUCTURE_ID);

CREATE TABLE IF NOT EXISTS  `b_hr_structure_node_path` (
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`PARENT_ID` bigint NOT NULL,
	`CHILD_ID` bigint NOT NULL,
	`DEPTH` bigint NOT NULL,
	UNIQUE INDEX UX_B_HR_NODE_PATH_PARENT_ID_CHILD_ID (`PARENT_ID`, `CHILD_ID`)
);

CREATE TABLE IF NOT EXISTS `b_hr_structure_role` (
	`ID` bigint AUTO_INCREMENT PRIMARY KEY,
	`ENTITY_TYPE` varchar(255) NOT NULL,
	`NAME` varchar(255) NOT NULL,
	`PRIORITY` bigint NOT NULL,
	`CHILD_AFFECTION_TYPE` int NOT NULL,
	`XML_ID` varchar(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS b_hr_access_role (
	ID bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	NAME varchar(250) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_hr_access_role_relation (
	ID bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_ID int UNSIGNED NOT NULL,
	RELATION varchar(8) NOT NULL,
	PRIMARY KEY (ID),
	INDEX IX_B_HR_ACCESS_ROLE_RELATION_ROLE_ID (ROLE_ID),
	INDEX IX_B_HR_ACCESS_ROLE_RELATION_RELATION (RELATION)
);

CREATE TABLE IF NOT EXISTS b_hr_access_permission (
	ID bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	ROLE_ID int UNSIGNED NOT NULL,
	PERMISSION_ID varchar(32) NOT NULL,
	VALUE tinyint UNSIGNED NOT NULL,
	PRIMARY KEY (ID),
	INDEX IX_B_HR_ACCESS_PERMISSION_ROLE_ID (ROLE_ID),
	INDEX IX_B_HR_ACCESS_PERMISSION_PERMISSION_ID (PERMISSION_ID),
	UNIQUE (ROLE_ID, PERMISSION_ID)
);

CREATE TABLE IF NOT EXISTS b_hr_log (
	ID bigint UNSIGNED NOT NULL AUTO_INCREMENT,
	DATE_CREATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MESSAGE varchar(255) DEFAULT NULL,
	ENTITY_TYPE varchar(50) DEFAULT NULL,
	ENTITY_ID bigint DEFAULT NULL,
	USER_ID int DEFAULT NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_HR_LOG_ENTITY_ID(ENTITY_ID),
	INDEX IX_B_HR_LOG_USER_ID(USER_ID)
);