<?php
if (!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true)
{
	die();
}

return [
	'css' => 'dist/project-wizard.bundle.css',
	'js' => 'dist/project-wizard.bundle.js',
	'rel' => [
		'main.core',
		'socialnetwork.v2.components.banners.new-project-banner',
		'socialnetwork.v2.components.elements.ui-accordion',
		'socialnetwork.v2.components.elements.ui-avatar-project',
		'socialnetwork.v2.components.elements.ui-checkbox',
		'socialnetwork.v2.components.elements.ui-divider',
		'socialnetwork.v2.components.elements.ui-field',
		'socialnetwork.v2.components.elements.ui-growing-text-area',
		'socialnetwork.v2.components.elements.ui-hint',
		'socialnetwork.v2.components.elements.ui-loader',
		'socialnetwork.v2.components.elements.ui-select',
		'socialnetwork.v2.components.elements.ui-switcher-field',
		'socialnetwork.v2.components.elements.ui-textarea',
		'socialnetwork.v2.components.popup.auto-delete-popup',
		'socialnetwork.v2.components.selectors.tags-selector',
		'socialnetwork.v2.components.selectors.users-selector',
		'socialnetwork.v2.const',
		'socialnetwork.v2.core',
		'socialnetwork.v2.features.project.copy-project-feature',
		'socialnetwork.v2.features.project.create-project-feature',
		'socialnetwork.v2.features.project.get-project-feature',
		'socialnetwork.v2.features.project.update-project-feature',
		'socialnetwork.v2.lib.calendar',
		'socialnetwork.v2.lib.timezone',
		'socialnetwork.v2.model.interface',
		'socialnetwork.v2.model.project',
		'socialnetwork.v2.provider.services.project-service',
		'ui.a11y',
		'ui.date-picker',
		'ui.icon-set.api.core',
		'ui.icon-set.api.vue',
		'ui.icon-set.outline',
		'ui.icon-set.solid',
		'ui.info-helper',
		'ui.notification-manager',
		'ui.switcher',
		'ui.system.input.vue',
		'ui.system.menu.vue',
		'ui.system.radiobutton',
		'ui.system.typography.vue',
		'ui.vue3',
		'ui.vue3.components.button',
		'ui.vue3.components.switcher',
		'ui.vue3.mixins.loc-mixin',
		'ui.vue3.pinia',
	],
	'skip_core' => false,
];
