<?php

return [
	'bundle' => [
		'./src/settings-service',
		'./src/settings-ui',
		'./src/crm-card',
		'./src/crm-summary-card',
		'./src/crm-settings-layout',
		'./src/calendar-card',
		'./src/outgoing-card',
		'./src/sharing-card',
		'./src/settings-layout',
	],
	'extensions' => [
		'loc',
		'tokens',
		'apptheme',
		'notify',
		'layout/pure-component',
		'mail:const',
		'asset-manager',
		'ui-system/typography/text',
		'ui-system/typography/heading',
		'ui-system/layout/area',
		'ui-system/layout/area-list',
		'ui-system/layout/card',
		'ui-system/layout/card-list',
		'ui-system/layout/dialog-footer',
		'ui-system/form/buttons/button',
		'ui-system/form/checkbox',
		'ui-system/blocks/switcher',
		'ui-system/blocks/link',
		'ui-system/blocks/icon',
		'ui-system/blocks/chips/chip-button',
		'ui-system/popups/popup-menu',
		'selector/widget/entity/socialnetwork/user',
		'elements-stack',
		'ui-system/blocks/avatar',
		'ui-system/form/inputs/string',
		'ui-system/form/inputs/number',
		'ui-system/form/inputs/textarea',
	],
];
